# Generated by Django 5.1.6 on 2025-02-15 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField(unique=True, verbose_name='table_number')),
                ('total_price', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='total_price')),
                ('status', models.CharField(choices=[('waiting', 'В ожидании'), ('done', 'Готово'), ('paid', 'Оплачено')], default='waiting', verbose_name='status')),
            ],
            options={
                'verbose_name': 'order',
                'db_table': 'order',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='order.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='orders', through='order.OrderItem', to='item.item', verbose_name='items'),
        ),
    ]
